#!/bin/bash

file1=$(cat $1)
file2=$(cat $2)
if [ "$file1" = "file2" ]; then
   echo "Mostly the same"
   exit 1
fi
diff -i $1 $2 > /dev/null
if [ $? -eq 0 ]; then
   echo "Mostly the same."
else 
 echo "Different."
fi
